Repository kalegd/DigitalBacon, pull requests merged in 2023-12, with the labels that each got.

#17 Add auto-tag and release-drafter github actions
  .github/release-drafter.yml
  .github/workflows/auto-tag.yml
  .github/workflows/release-drafter.yml
Labels: feature request

#12 adding eslint package and config
  .eslintrc.json
  package.json
Labels: feature request

#19 Update eslint indent options and apply auto fix from eslint
  .eslintrc.json
  package.json
  scripts/core/Main.js
  scripts/core/assets/BasicMovement.js
  scripts/core/assets/PeerController.js
  scripts/core/assets/UserController.js
  scripts/core/clients/GoogleDrive.js
  scripts/core/clients/RTCPeer.js
  scripts/core/clients/ReadyPlayerMe.js
  scripts/core/clients/Sketchfab.js
  scripts/core/enums/Handedness.js
  scripts/core/handlers/CopyPasteControlsHandler.js
  scripts/core/handlers/InputHandler.js
  scripts/core/handlers/LibraryHandler.js
  scripts/core/handlers/PartyHandler.js
  scripts/core/handlers/PointerInteractableHandler.js
  scripts/core/handlers/PubSub.js
  scripts/core/handlers/SessionHandler.js
  scripts/core/handlers/TransformControlsHandler.js
  scripts/core/handlers/hands/ScaleHandler.js
  scripts/core/helpers/Box3Helper.js
  scripts/core/helpers/NotificationHub.js
  scripts/core/helpers/PartyMessageHelper.js
  scripts/core/helpers/ThreeMeshUIHelper.js
  scripts/core/helpers/constants.js
  scripts/core/helpers/editor/AssetEntityHelper.js
  scripts/core/helpers/editor/AudioAssetHelper.js
  scripts/core/helpers/editor/EditorHelper.js
  scripts/core/helpers/editor/MaterialHelper.js
  scripts/core/helpers/editor/ShapeHelper.js
  scripts/core/helpers/editor/VideoAssetHelper.js
  scripts/core/helpers/utils.module.js
  scripts/core/menu/MenuController.js
  scripts/core/menu/NotificationHub.js
  scripts/core/menu/input/EulerInput.js
  scripts/core/menu/input/Keyboard.js
  scripts/core/menu/input/TextureInput.js
  scripts/core/menu/pages/EditAcknowledgementsPage.js
  scripts/core/menu/pages/EditorSettingsPage.js
  scripts/core/menu/pages/HostPartyPage.js
  scripts/core/menu/pages/LibraryPage.js
  scripts/core/menu/pages/NewAssetPage.js
  scripts/core/menu/pages/SketchfabLoginPage.js
  scripts/core/menu/pages/SketchfabSearchPage.js
  scripts/core/menu/pages/UserSettingsPage.js
  scripts/core/setup.js
Labels: bug

#21 Add gifs to README
  README.md
  resources/gifs/ar_wall_occlusion_demo.gif
  resources/gifs/iphone_demo.gif
  resources/gifs/vr_asset_transform_demo.gif
  resources/gifs/water_color_demo.gif
Labels: documentation, community

#23 Add GitHub action to run eslint on pull requests
  .github/workflows/ci.yml
Labels: feature request

#26 Add jest for testing with test file for PubSub
  package-lock.json
  package.json
  test/scripts/core/handlers/PubSub.test.js
Labels: feature request

#34 Add update-build.yml GitHub action workflow
  .github/workflows/update-build.yml
Labels: feature request
